FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY packages/shared/package.json ./packages/shared/
COPY apps/api/package.json ./apps/api/
COPY apps/web/package.json ./apps/web/

RUN pnpm install

COPY packages/shared ./packages/shared
COPY apps/api ./apps/api

WORKDIR /usr/src/app/apps/api

RUN pnpm --filter @ratehub/shared build
RUN pnpm prisma generate

EXPOSE 3000

CMD ["pnpm", "start:dev"]
